# Generated by Django 5.0 on 2024-03-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_shop', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='re_enter',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
