# Generated by Django 5.0 on 2024-03-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_shop', '0006_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='re_enter',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
